# Generated by Django 4.1.3 on 2022-11-23 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('gradset', models.CharField(blank=True, choices=[('0', 'SET 2021'), ('1', 'SET 2020'), ('2', 'SET 2019'), ('3', 'SET 2018'), ('4', 'SET 2017'), ('5', 'SET 2016'), ('6', 'SET 2015'), ('7', 'SET 2014'), ('8', 'SET 2013'), ('9', 'SET 2012'), ('10', 'SET 2011'), ('11', 'SET 2010'), ('12', 'SET 2009'), ('13', 'SET 2008'), ('14', 'SET 2007'), ('15', 'SET 2006'), ('16', 'SET 2005'), ('17', 'SET 2004'), ('18', 'SET 2003'), ('19', 'SET 2002'), ('20', 'SET 2001')], max_length=50)),
                ('house', models.CharField(blank=True, choices=[('mande', 'Mande House'), ('abugh', 'Abu House'), ('kuma', 'Kuma House'), ('pine', 'Pine House')], max_length=50)),
                ('profileimg', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('relationship', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
