# Generated by Django 4.1.3 on 2022-11-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_followerscount_likepost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gradset',
            field=models.CharField(blank=True, choices=[('SET 2021', 'SET 2021'), ('SET 2020', 'SET 2020'), ('SET 2019', 'SET 2019'), ('SET 2018', 'SET 2018'), ('SET 2017', 'SET 2017'), ('SET 2016', 'SET 2016'), ('SET 2015', 'SET 2015'), ('SET 2014', 'SET 2014'), ('SET 2013', 'SET 2013'), ('SET 2012', 'SET 2012'), ('SET 2011', 'SET 2011'), ('SET 2010', 'SET 2010'), ('SET 2009', 'SET 2009'), ('SET 2008', 'SET 2008'), ('SET 2007', 'SET 2007'), ('SET 2006', 'SET 2006'), ('SET 2005', 'SET 2005'), ('SET 2004', 'SET 2004'), ('SET 2003', 'SET 2003'), ('SET 2002', 'SET 2002'), ('SET 2001', 'SET 2001')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='house',
            field=models.CharField(blank=True, choices=[('Mande House', 'Mande House'), ('Abugh House', 'Abugh House'), ('Kuma House', 'Kuma House'), ('Pine House', 'Pine House')], max_length=50),
        ),
    ]
